- ansible.builtin.debug:
    msg: "Creating User {{ user.username }}"
  name: "User Name"
- name: "Create User"
  uri:
    validate_certs: false
    body: "{{ user | to_json }}"
    body_format: json
    headers:
      Accept: application/json
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
      Content-type: application/json
    method: POST
    status_code:
      - 201
      - 409
    url: "{{ auth_keycloak_url }}/admin/realms/{{ realm_name }}/users"
